# Generated by Django 3.2.15 on 2022-08-18 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedTPayCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_token', models.CharField(max_length=255, verbose_name='Card token')),
                ('card_expiration_code', models.CharField(default='0000', max_length=4, verbose_name='Card expiration code')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Last used')),
            ],
            options={
                'verbose_name': 'Saved TPay Card',
                'verbose_name_plural': 'Saved TPay Cards.',
            },
        ),
        migrations.CreateModel(
            name='TPayPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('number', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='UUID Payment number')),
                ('transaction_id', models.CharField(max_length=255, verbose_name='Transaction ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TPay Payment',
                'verbose_name_plural': 'TPay Payments',
                'ordering': ['-created_dt'],
            },
        ),
    ]
